eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging.level.root: DEBUG
server:
  port: 9411
spring:
  application:
    name: zipkin-server
#spring.sleuth.sampler.percentage: 1.0
armeria:
  ports:
    - port: 9411
      protocol: HTTP