server:
  port: 8761
management.endpoint.httptrace.enabled: true
management.endpoint.httptrace.repository-type: in-memory
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/