eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 5000
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
  cloud:
    discovery:
      reactive:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-a
          uri: lb://user-service

          predicates:
            - Path=/user-api/**
          filters:
            - StripPrefix=1

